services:
  postgres:
    image: postgres:latest
    container_name: ${DB_NAME}-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:${DB_PORT}'
    volumes:
      - ./.database:/var/lib/postgresql/data
